# -*- coding: utf-8 -*-
"""DATM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1264GcHjlrgDu6p0CLih09rUTUL2F4-rV
"""

# food_label_app.py

import streamlit as st
import pytesseract
from PIL import Image
import re
from collections import Counter
from rapidfuzz import fuzz
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
st.set_page_config(page_title="Food Label Decoder", page_icon="🥗", layout="wide")
# Tesseract path
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# -------------------------------
# CONFIG
# -------------------------------
st.markdown("""
<h1 style='margin-bottom:5px;'>🥗 Food Label Decoder</h1>
<p style='font-size:16px; color:gray;'>AI-powered ingredient analysis</p>
""", unsafe_allow_html=True)

st.markdown("""
<style>
ul {
    margin-top: 0px;
    margin-bottom: 0px;
    line-height: 1.2;
}
li {
    margin-bottom: 2px;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
.block-container {
    padding-top: 2.5rem;  /* FIX: increase top spacing */
    padding-bottom: 1rem;
}

h1 {
    margin-top: 0px;
    margin-bottom: 5px;
}

p {
    margin-top: 0px;
}
</style>
""", unsafe_allow_html=True)
# -------------------------------
# CONSTANTS (Knowledge Base)
# -------------------------------
HIDDEN_SUGARS = [
    "sugar", "glucose", "fructose", "corn syrup", "glucose-fructose syrup",
    "hfcs", "dextrose", "maltose", "sucrose"
]

PALM_OIL = ["palm oil", "palm fat"]

HIGH_SODIUM = ["sodium", "monosodium glutamate", "sodium benzoate", "e250", "e251"]

ARTIFICIAL_ADDITIVES = ["e102", "e110", "e124", "e129", "e150", "e133", "e155"]

# -------------------------------
# UTILS (IMPROVED OCR CLEANING)
# -------------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9,()\-\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces
    return text.strip()

def extract_ingredients(text):
    text = clean_text(text)
    parts = re.split(r',|\(|\)', text)
    parts = [p.strip() for p in parts if len(p.strip()) > 2]
    return list(set(parts))

def fuzzy_match(item, keywords, threshold=85):
    for key in keywords:
        if fuzz.partial_ratio(item, key) >= threshold:
            return True
    return False

# -------------------------------
# DETECTION
# -------------------------------
def detect_categories(ingredients):
    results = {
        "Hidden Sugar": [],
        "Palm Oil": [],
        "High Sodium": [],
        "Artificial Additives": []
    }

    for ing in ingredients:
        if fuzzy_match(ing, HIDDEN_SUGARS):
            results["Hidden Sugar"].append(ing)

        elif fuzzy_match(ing, PALM_OIL):
            results["Palm Oil"].append(ing)

        elif fuzzy_match(ing, HIGH_SODIUM):
            results["High Sodium"].append(ing)

        elif re.search(r'\be\d{3}\b', ing):
            results["Artificial Additives"].append(ing)

    return results

# -------------------------------
# RISK
# -------------------------------
def calculate_risk(results):
    score = (
        len(results["Hidden Sugar"]) * 2 +
        len(results["Palm Oil"]) * 2 +
        len(results["High Sodium"]) * 1.5 +
        len(results["Artificial Additives"]) * 1
    )

    if score > 8:
        return "High", score
    elif score > 4:
        return "Medium", score
    else:
        return "Low", score

# -------------------------------
# CLUSTERING
# -------------------------------
def cluster_ingredients(ingredients, k=4):
    if len(ingredients) < 2:
        return {0: ingredients}

    k = min(k, len(ingredients))

    vectorizer = TfidfVectorizer(ngram_range=(1, 2))
    X = vectorizer.fit_transform(ingredients)

    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X)

    clusters = {}
    for i, label in enumerate(labels):
        clusters.setdefault(label, []).append(ingredients[i])

    return clusters, X, labels

def interpret_cluster(cluster_items):
    category_scores = {
        "Hidden Sugar": 0,
        "Palm Oil": 0,
        "High Sodium": 0,
        "Artificial Additives": 0,
        "Base Ingredients": 0  # ✅ MUST EXIST HERE
    }

    for item in cluster_items:
        if fuzzy_match(item, HIDDEN_SUGARS):
            category_scores["Hidden Sugar"] += 1

        elif fuzzy_match(item, PALM_OIL):
            category_scores["Palm Oil"] += 1

        elif fuzzy_match(item, HIGH_SODIUM):
            category_scores["High Sodium"] += 1

        elif re.search(r'\be\d{3}\b', item):
            category_scores["Artificial Additives"] += 1

        else:
            category_scores["Base Ingredients"] += 1  # ✅ NOW SAFE

    dominant = max(category_scores, key=category_scores.get)
    return dominant, category_scores

# -------------------------------
# UI
# -------------------------------

uploaded_file = st.file_uploader("Upload Image", type=["jpg", "png", "jpeg"])

if uploaded_file:

    image = Image.open(uploaded_file)

    # OCR + CLEANING
    raw_text = pytesseract.image_to_string(image)
    extracted_text = clean_text(raw_text)

    # Extract ingredients
    ingredients = extract_ingredients(extracted_text)

    # 🔥 SIDE-BY-SIDE LAYOUT
    left, right = st.columns([1, 1])

    with left:
        st.image(image, caption="Uploaded Image", use_container_width=True)

    with right:
        st.subheader("🧾 Extracted Ingredients")

        MAX_DISPLAY = 12
        for ing in ingredients[:MAX_DISPLAY]:
            st.markdown(f"- {ing}")

        if len(ingredients) > MAX_DISPLAY:
            with st.expander("Show all ingredients"):
                for ing in ingredients:
                    st.write(f"• {ing}")
    # -------------------------------
    # CATEGORY DETECTION
    # -------------------------------
    results = detect_categories(ingredients)

    risk, score = calculate_risk(results)

    st.subheader("⚠ Analysis Result")

    # Choose color based on risk
    if risk == "High":
        color = "#ffcccc"
    elif risk == "Medium":
        color = "#fff3cd"
    else:
        color = "#d4edda"

    st.markdown(f"""
    <div style='padding:8px; border-radius:6px; background-color:{color};'>
    <b>Risk Level:</b> {risk} &nbsp;&nbsp; | &nbsp;&nbsp; <b>Score:</b> {score}
    </div>
    """, unsafe_allow_html=True)

    st.caption("Risk score is based on weighted harmful ingredient categories.")

    # -------------------------------
    # DETECTED INGREDIENTS
    # -------------------------------
    st.subheader("🚨 Detected Harmful Ingredients")

    for category, items in results.items():
        if items:
            counts = Counter(items)
            st.write(f"### {category} ({len(items)} detected)")
            for item, count in counts.items():
                st.write(f"- {item} (x{count})")

    # -------------------------------
    # CLUSTERING
    # -------------------------------
    st.subheader("🧠 Ingredient Clusters (AI Grouping)")

    clusters, X, labels = cluster_ingredients(ingredients)

    # -------------------------------
    # CLUSTER METRICS
    # -------------------------------
    if len(ingredients) > 2:
        sil_score = silhouette_score(X, labels)
        db_score = davies_bouldin_score(X.toarray(), labels)

        st.subheader("📈 Clustering Performance")

        st.write(f"Silhouette Score: {round(sil_score, 2)}")
        st.write(f"Davies-Bouldin Index: {round(db_score, 2)}")

    for cluster_id, items in clusters.items():
        label, scores = interpret_cluster(items)

        with st.container():
            st.markdown(f"### 🔹 Cluster {cluster_id + 1}: **{label}**")

            col1, col2 = st.columns([2,1])

            with col1:
                for item in items:
                    st.write(f"• {item}")

            with col2:
                st.markdown("**Category Breakdown:**")
                for k, v in scores.items():
                    if v > 0:
                        st.write(f"{k}: {v}")

    # 🔥 NEW: CLUSTER INSIGHTS
    st.subheader("📊 Cluster Insights")

    for cluster_id, items in clusters.items():
        label, _ = interpret_cluster(items)
        st.write(f"Cluster {cluster_id + 1} is mainly **{label}** with {len(items)} ingredients.")

    # -------------------------------
    # INSIGHTS
    # -------------------------------
    st.subheader("💡 Health Insights")

    if results["Hidden Sugar"]:
        st.warning("High sugar intake may lead to obesity and diabetes.")

    if results["Palm Oil"]:
        st.warning("Palm oil is high in saturated fats, linked to heart issues.")

    if results["High Sodium"]:
        st.warning("High sodium intake can increase blood pressure.")

    if results["Artificial Additives"]:
        st.warning("Artificial additives may have long-term health effects.")